package com.ibms.app.dao;

import com.ibms.app.beans.CecDoorOpen;

public interface CecDoorOpenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_DOOR_OPEN
     *
     * @mbggenerated
     */
    int insert(CecDoorOpen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_DOOR_OPEN
     *
     * @mbggenerated
     */
    int insertSelective(CecDoorOpen record);
}