package com.ibms.app.dao;

import com.ibms.app.beans.CecDeviceInfoValue;

import java.util.List;

public interface CecDeviceInfoValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_DEVICE_INFO_VALUE
     *
     * @mbggenerated
     */
    int insert(CecDeviceInfoValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_DEVICE_INFO_VALUE
     *
     * @mbggenerated
     */
    int insertSelective(CecDeviceInfoValue record);

    List<CecDeviceInfoValue> selectByBean(CecDeviceInfoValue cecDeviceInfoValue);

    int updateSelective(CecDeviceInfoValue cecDeviceInfoValue);
}