package com.ibms.app.dao;

import com.ibms.app.beans.CecEquipment;

import java.util.List;

public interface CecEquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    int insert(CecEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    int insertSelective(CecEquipment record);


    /**
     * 搜索全部设备
     */
    List<CecEquipment> selectAllByCondition();
}