package com.ibms.app.dao;

import com.ibms.app.beans.CecEquipment;
import com.ibms.app.beans.CecEquipmentExample;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

public interface CecEquipmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    int insert(CecEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    int insertSelective(CecEquipment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    List<CecEquipment> selectByExample(CecEquipmentExample example);
}