package com.ibms.app.beans;

import java.util.Date;

public class CecAlarmHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.ALARM_TIME
     *
     * @mbggenerated
     */
    private Date alarmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.COM_CODE
     *
     * @mbggenerated
     */
    private String comCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.DEV_CODE
     *
     * @mbggenerated
     */
    private String devCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.INF_CODE
     *
     * @mbggenerated
     */
    private String infCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.VALUE
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.LEVEL_CODE
     *
     * @mbggenerated
     */
    private String levelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.ALARM_DESC
     *
     * @mbggenerated
     */
    private String alarmDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.PROCESS
     *
     * @mbggenerated
     */
    private String process;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.FLOOR
     *
     * @mbggenerated
     */
    private String floor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.LOCATION
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.ALARM_POINT
     *
     * @mbggenerated
     */
    private String alarmPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.END_ALARM_TIME
     *
     * @mbggenerated
     */
    private Date endAlarmTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.PERSIST_TIME
     *
     * @mbggenerated
     */
    private String persistTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_ALARM_HISTORY.CLASSIFY_CODE
     *
     * @mbggenerated
     */
    private String classifyCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.ALARM_TIME
     *
     * @return the value of CEC_ALARM_HISTORY.ALARM_TIME
     *
     * @mbggenerated
     */
    public Date getAlarmTime() {
        return alarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.ALARM_TIME
     *
     * @param alarmTime the value for CEC_ALARM_HISTORY.ALARM_TIME
     *
     * @mbggenerated
     */
    public void setAlarmTime(Date alarmTime) {
        this.alarmTime = alarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.COM_CODE
     *
     * @return the value of CEC_ALARM_HISTORY.COM_CODE
     *
     * @mbggenerated
     */
    public String getComCode() {
        return comCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.COM_CODE
     *
     * @param comCode the value for CEC_ALARM_HISTORY.COM_CODE
     *
     * @mbggenerated
     */
    public void setComCode(String comCode) {
        this.comCode = comCode == null ? null : comCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.DEV_CODE
     *
     * @return the value of CEC_ALARM_HISTORY.DEV_CODE
     *
     * @mbggenerated
     */
    public String getDevCode() {
        return devCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.DEV_CODE
     *
     * @param devCode the value for CEC_ALARM_HISTORY.DEV_CODE
     *
     * @mbggenerated
     */
    public void setDevCode(String devCode) {
        this.devCode = devCode == null ? null : devCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.INF_CODE
     *
     * @return the value of CEC_ALARM_HISTORY.INF_CODE
     *
     * @mbggenerated
     */
    public String getInfCode() {
        return infCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.INF_CODE
     *
     * @param infCode the value for CEC_ALARM_HISTORY.INF_CODE
     *
     * @mbggenerated
     */
    public void setInfCode(String infCode) {
        this.infCode = infCode == null ? null : infCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.VALUE
     *
     * @return the value of CEC_ALARM_HISTORY.VALUE
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.VALUE
     *
     * @param value the value for CEC_ALARM_HISTORY.VALUE
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.LEVEL_CODE
     *
     * @return the value of CEC_ALARM_HISTORY.LEVEL_CODE
     *
     * @mbggenerated
     */
    public String getLevelCode() {
        return levelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.LEVEL_CODE
     *
     * @param levelCode the value for CEC_ALARM_HISTORY.LEVEL_CODE
     *
     * @mbggenerated
     */
    public void setLevelCode(String levelCode) {
        this.levelCode = levelCode == null ? null : levelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.ALARM_DESC
     *
     * @return the value of CEC_ALARM_HISTORY.ALARM_DESC
     *
     * @mbggenerated
     */
    public String getAlarmDesc() {
        return alarmDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.ALARM_DESC
     *
     * @param alarmDesc the value for CEC_ALARM_HISTORY.ALARM_DESC
     *
     * @mbggenerated
     */
    public void setAlarmDesc(String alarmDesc) {
        this.alarmDesc = alarmDesc == null ? null : alarmDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.PROCESS
     *
     * @return the value of CEC_ALARM_HISTORY.PROCESS
     *
     * @mbggenerated
     */
    public String getProcess() {
        return process;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.PROCESS
     *
     * @param process the value for CEC_ALARM_HISTORY.PROCESS
     *
     * @mbggenerated
     */
    public void setProcess(String process) {
        this.process = process == null ? null : process.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.FLOOR
     *
     * @return the value of CEC_ALARM_HISTORY.FLOOR
     *
     * @mbggenerated
     */
    public String getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.FLOOR
     *
     * @param floor the value for CEC_ALARM_HISTORY.FLOOR
     *
     * @mbggenerated
     */
    public void setFloor(String floor) {
        this.floor = floor == null ? null : floor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.LOCATION
     *
     * @return the value of CEC_ALARM_HISTORY.LOCATION
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.LOCATION
     *
     * @param location the value for CEC_ALARM_HISTORY.LOCATION
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.ALARM_POINT
     *
     * @return the value of CEC_ALARM_HISTORY.ALARM_POINT
     *
     * @mbggenerated
     */
    public String getAlarmPoint() {
        return alarmPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.ALARM_POINT
     *
     * @param alarmPoint the value for CEC_ALARM_HISTORY.ALARM_POINT
     *
     * @mbggenerated
     */
    public void setAlarmPoint(String alarmPoint) {
        this.alarmPoint = alarmPoint == null ? null : alarmPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.END_ALARM_TIME
     *
     * @return the value of CEC_ALARM_HISTORY.END_ALARM_TIME
     *
     * @mbggenerated
     */
    public Date getEndAlarmTime() {
        return endAlarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.END_ALARM_TIME
     *
     * @param endAlarmTime the value for CEC_ALARM_HISTORY.END_ALARM_TIME
     *
     * @mbggenerated
     */
    public void setEndAlarmTime(Date endAlarmTime) {
        this.endAlarmTime = endAlarmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.PERSIST_TIME
     *
     * @return the value of CEC_ALARM_HISTORY.PERSIST_TIME
     *
     * @mbggenerated
     */
    public String getPersistTime() {
        return persistTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.PERSIST_TIME
     *
     * @param persistTime the value for CEC_ALARM_HISTORY.PERSIST_TIME
     *
     * @mbggenerated
     */
    public void setPersistTime(String persistTime) {
        this.persistTime = persistTime == null ? null : persistTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_ALARM_HISTORY.CLASSIFY_CODE
     *
     * @return the value of CEC_ALARM_HISTORY.CLASSIFY_CODE
     *
     * @mbggenerated
     */
    public String getClassifyCode() {
        return classifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_ALARM_HISTORY.CLASSIFY_CODE
     *
     * @param classifyCode the value for CEC_ALARM_HISTORY.CLASSIFY_CODE
     *
     * @mbggenerated
     */
    public void setClassifyCode(String classifyCode) {
        this.classifyCode = classifyCode == null ? null : classifyCode.trim();
    }
}