package com.ibms.app.beans;

import java.util.Date;

public class CecDoorOpen {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_DOOR_OPEN.CardID
     *
     * @mbggenerated
     */
    private String cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_DOOR_OPEN.OpenDate
     *
     * @mbggenerated
     */
    private Date opendate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_DOOR_OPEN.CardID
     *
     * @return the value of CEC_DOOR_OPEN.CardID
     *
     * @mbggenerated
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_DOOR_OPEN.CardID
     *
     * @param cardid the value for CEC_DOOR_OPEN.CardID
     *
     * @mbggenerated
     */
    public void setCardid(String cardid) {
        this.cardid = cardid == null ? null : cardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_DOOR_OPEN.OpenDate
     *
     * @return the value of CEC_DOOR_OPEN.OpenDate
     *
     * @mbggenerated
     */
    public Date getOpendate() {
        return opendate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_DOOR_OPEN.OpenDate
     *
     * @param opendate the value for CEC_DOOR_OPEN.OpenDate
     *
     * @mbggenerated
     */
    public void setOpendate(Date opendate) {
        this.opendate = opendate;
    }
}