package com.ibms.app.beans;

import java.util.Date;

public class CecDeviceInfoValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_DEVICE_INFO_VALUE.COM_CODE
     *
     * @mbggenerated
     */
    private String comCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_DEVICE_INFO_VALUE.DEV_CODE
     *
     * @mbggenerated
     */
    private String devCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_DEVICE_INFO_VALUE.INF_CODE
     *
     * @mbggenerated
     */
    private String infCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_DEVICE_INFO_VALUE.CURR_VALUE
     *
     * @mbggenerated
     */
    private String currValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_DEVICE_INFO_VALUE.CURR_TIME
     *
     * @mbggenerated
     */
    private Date currTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_DEVICE_INFO_VALUE.COM_CODE
     *
     * @return the value of CEC_DEVICE_INFO_VALUE.COM_CODE
     *
     * @mbggenerated
     */
    public String getComCode() {
        return comCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_DEVICE_INFO_VALUE.COM_CODE
     *
     * @param comCode the value for CEC_DEVICE_INFO_VALUE.COM_CODE
     *
     * @mbggenerated
     */
    public void setComCode(String comCode) {
        this.comCode = comCode == null ? null : comCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_DEVICE_INFO_VALUE.DEV_CODE
     *
     * @return the value of CEC_DEVICE_INFO_VALUE.DEV_CODE
     *
     * @mbggenerated
     */
    public String getDevCode() {
        return devCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_DEVICE_INFO_VALUE.DEV_CODE
     *
     * @param devCode the value for CEC_DEVICE_INFO_VALUE.DEV_CODE
     *
     * @mbggenerated
     */
    public void setDevCode(String devCode) {
        this.devCode = devCode == null ? null : devCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_DEVICE_INFO_VALUE.INF_CODE
     *
     * @return the value of CEC_DEVICE_INFO_VALUE.INF_CODE
     *
     * @mbggenerated
     */
    public String getInfCode() {
        return infCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_DEVICE_INFO_VALUE.INF_CODE
     *
     * @param infCode the value for CEC_DEVICE_INFO_VALUE.INF_CODE
     *
     * @mbggenerated
     */
    public void setInfCode(String infCode) {
        this.infCode = infCode == null ? null : infCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_DEVICE_INFO_VALUE.CURR_VALUE
     *
     * @return the value of CEC_DEVICE_INFO_VALUE.CURR_VALUE
     *
     * @mbggenerated
     */
    public String getCurrValue() {
        return currValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_DEVICE_INFO_VALUE.CURR_VALUE
     *
     * @param currValue the value for CEC_DEVICE_INFO_VALUE.CURR_VALUE
     *
     * @mbggenerated
     */
    public void setCurrValue(String currValue) {
        this.currValue = currValue == null ? null : currValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_DEVICE_INFO_VALUE.CURR_TIME
     *
     * @return the value of CEC_DEVICE_INFO_VALUE.CURR_TIME
     *
     * @mbggenerated
     */
    public Date getCurrTime() {
        return currTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_DEVICE_INFO_VALUE.CURR_TIME
     *
     * @param currTime the value for CEC_DEVICE_INFO_VALUE.CURR_TIME
     *
     * @mbggenerated
     */
    public void setCurrTime(Date currTime) {
        this.currTime = currTime;
    }
}