package com.ibms.app.beans;

import java.util.ArrayList;
import java.util.List;

public class CecEquipmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    public CecEquipmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEquipmentIdIsNull() {
            addCriterion("EQUIPMENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIsNotNull() {
            addCriterion("EQUIPMENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdEqualTo(String value) {
            addCriterion("EQUIPMENT_ID =", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotEqualTo(String value) {
            addCriterion("EQUIPMENT_ID <>", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdGreaterThan(String value) {
            addCriterion("EQUIPMENT_ID >", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIPMENT_ID >=", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLessThan(String value) {
            addCriterion("EQUIPMENT_ID <", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLessThanOrEqualTo(String value) {
            addCriterion("EQUIPMENT_ID <=", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdLike(String value) {
            addCriterion("EQUIPMENT_ID like", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotLike(String value) {
            addCriterion("EQUIPMENT_ID not like", value, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdIn(List<String> values) {
            addCriterion("EQUIPMENT_ID in", values, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotIn(List<String> values) {
            addCriterion("EQUIPMENT_ID not in", values, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdBetween(String value1, String value2) {
            addCriterion("EQUIPMENT_ID between", value1, value2, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentIdNotBetween(String value1, String value2) {
            addCriterion("EQUIPMENT_ID not between", value1, value2, "equipmentId");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameIsNull() {
            addCriterion("EQUIPMENT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameIsNotNull() {
            addCriterion("EQUIPMENT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameEqualTo(String value) {
            addCriterion("EQUIPMENT_NAME =", value, "equipmentName");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameNotEqualTo(String value) {
            addCriterion("EQUIPMENT_NAME <>", value, "equipmentName");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameGreaterThan(String value) {
            addCriterion("EQUIPMENT_NAME >", value, "equipmentName");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIPMENT_NAME >=", value, "equipmentName");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameLessThan(String value) {
            addCriterion("EQUIPMENT_NAME <", value, "equipmentName");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameLessThanOrEqualTo(String value) {
            addCriterion("EQUIPMENT_NAME <=", value, "equipmentName");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameLike(String value) {
            addCriterion("EQUIPMENT_NAME like", value, "equipmentName");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameNotLike(String value) {
            addCriterion("EQUIPMENT_NAME not like", value, "equipmentName");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameIn(List<String> values) {
            addCriterion("EQUIPMENT_NAME in", values, "equipmentName");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameNotIn(List<String> values) {
            addCriterion("EQUIPMENT_NAME not in", values, "equipmentName");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameBetween(String value1, String value2) {
            addCriterion("EQUIPMENT_NAME between", value1, value2, "equipmentName");
            return (Criteria) this;
        }

        public Criteria andEquipmentNameNotBetween(String value1, String value2) {
            addCriterion("EQUIPMENT_NAME not between", value1, value2, "equipmentName");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdIsNull() {
            addCriterion("EQUIPMENT_TYPE_ID is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdIsNotNull() {
            addCriterion("EQUIPMENT_TYPE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdEqualTo(String value) {
            addCriterion("EQUIPMENT_TYPE_ID =", value, "equipmentTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdNotEqualTo(String value) {
            addCriterion("EQUIPMENT_TYPE_ID <>", value, "equipmentTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdGreaterThan(String value) {
            addCriterion("EQUIPMENT_TYPE_ID >", value, "equipmentTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIPMENT_TYPE_ID >=", value, "equipmentTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdLessThan(String value) {
            addCriterion("EQUIPMENT_TYPE_ID <", value, "equipmentTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdLessThanOrEqualTo(String value) {
            addCriterion("EQUIPMENT_TYPE_ID <=", value, "equipmentTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdLike(String value) {
            addCriterion("EQUIPMENT_TYPE_ID like", value, "equipmentTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdNotLike(String value) {
            addCriterion("EQUIPMENT_TYPE_ID not like", value, "equipmentTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdIn(List<String> values) {
            addCriterion("EQUIPMENT_TYPE_ID in", values, "equipmentTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdNotIn(List<String> values) {
            addCriterion("EQUIPMENT_TYPE_ID not in", values, "equipmentTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdBetween(String value1, String value2) {
            addCriterion("EQUIPMENT_TYPE_ID between", value1, value2, "equipmentTypeId");
            return (Criteria) this;
        }

        public Criteria andEquipmentTypeIdNotBetween(String value1, String value2) {
            addCriterion("EQUIPMENT_TYPE_ID not between", value1, value2, "equipmentTypeId");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNull() {
            addCriterion("REGION_ID is null");
            return (Criteria) this;
        }

        public Criteria andRegionIdIsNotNull() {
            addCriterion("REGION_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRegionIdEqualTo(String value) {
            addCriterion("REGION_ID =", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotEqualTo(String value) {
            addCriterion("REGION_ID <>", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThan(String value) {
            addCriterion("REGION_ID >", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdGreaterThanOrEqualTo(String value) {
            addCriterion("REGION_ID >=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThan(String value) {
            addCriterion("REGION_ID <", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLessThanOrEqualTo(String value) {
            addCriterion("REGION_ID <=", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdLike(String value) {
            addCriterion("REGION_ID like", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotLike(String value) {
            addCriterion("REGION_ID not like", value, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdIn(List<String> values) {
            addCriterion("REGION_ID in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotIn(List<String> values) {
            addCriterion("REGION_ID not in", values, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdBetween(String value1, String value2) {
            addCriterion("REGION_ID between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andRegionIdNotBetween(String value1, String value2) {
            addCriterion("REGION_ID not between", value1, value2, "regionId");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeIsNull() {
            addCriterion("EQUIPMENT_CODE is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeIsNotNull() {
            addCriterion("EQUIPMENT_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeEqualTo(String value) {
            addCriterion("EQUIPMENT_CODE =", value, "equipmentCode");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeNotEqualTo(String value) {
            addCriterion("EQUIPMENT_CODE <>", value, "equipmentCode");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeGreaterThan(String value) {
            addCriterion("EQUIPMENT_CODE >", value, "equipmentCode");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIPMENT_CODE >=", value, "equipmentCode");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeLessThan(String value) {
            addCriterion("EQUIPMENT_CODE <", value, "equipmentCode");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeLessThanOrEqualTo(String value) {
            addCriterion("EQUIPMENT_CODE <=", value, "equipmentCode");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeLike(String value) {
            addCriterion("EQUIPMENT_CODE like", value, "equipmentCode");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeNotLike(String value) {
            addCriterion("EQUIPMENT_CODE not like", value, "equipmentCode");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeIn(List<String> values) {
            addCriterion("EQUIPMENT_CODE in", values, "equipmentCode");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeNotIn(List<String> values) {
            addCriterion("EQUIPMENT_CODE not in", values, "equipmentCode");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeBetween(String value1, String value2) {
            addCriterion("EQUIPMENT_CODE between", value1, value2, "equipmentCode");
            return (Criteria) this;
        }

        public Criteria andEquipmentCodeNotBetween(String value1, String value2) {
            addCriterion("EQUIPMENT_CODE not between", value1, value2, "equipmentCode");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressIsNull() {
            addCriterion("EQUIPMENT_ADDRESS is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressIsNotNull() {
            addCriterion("EQUIPMENT_ADDRESS is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressEqualTo(String value) {
            addCriterion("EQUIPMENT_ADDRESS =", value, "equipmentAddress");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressNotEqualTo(String value) {
            addCriterion("EQUIPMENT_ADDRESS <>", value, "equipmentAddress");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressGreaterThan(String value) {
            addCriterion("EQUIPMENT_ADDRESS >", value, "equipmentAddress");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIPMENT_ADDRESS >=", value, "equipmentAddress");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressLessThan(String value) {
            addCriterion("EQUIPMENT_ADDRESS <", value, "equipmentAddress");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressLessThanOrEqualTo(String value) {
            addCriterion("EQUIPMENT_ADDRESS <=", value, "equipmentAddress");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressLike(String value) {
            addCriterion("EQUIPMENT_ADDRESS like", value, "equipmentAddress");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressNotLike(String value) {
            addCriterion("EQUIPMENT_ADDRESS not like", value, "equipmentAddress");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressIn(List<String> values) {
            addCriterion("EQUIPMENT_ADDRESS in", values, "equipmentAddress");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressNotIn(List<String> values) {
            addCriterion("EQUIPMENT_ADDRESS not in", values, "equipmentAddress");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressBetween(String value1, String value2) {
            addCriterion("EQUIPMENT_ADDRESS between", value1, value2, "equipmentAddress");
            return (Criteria) this;
        }

        public Criteria andEquipmentAddressNotBetween(String value1, String value2) {
            addCriterion("EQUIPMENT_ADDRESS not between", value1, value2, "equipmentAddress");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedIsNull() {
            addCriterion("IS_ISOLATED is null");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedIsNotNull() {
            addCriterion("IS_ISOLATED is not null");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedEqualTo(String value) {
            addCriterion("IS_ISOLATED =", value, "isIsolated");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedNotEqualTo(String value) {
            addCriterion("IS_ISOLATED <>", value, "isIsolated");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedGreaterThan(String value) {
            addCriterion("IS_ISOLATED >", value, "isIsolated");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedGreaterThanOrEqualTo(String value) {
            addCriterion("IS_ISOLATED >=", value, "isIsolated");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedLessThan(String value) {
            addCriterion("IS_ISOLATED <", value, "isIsolated");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedLessThanOrEqualTo(String value) {
            addCriterion("IS_ISOLATED <=", value, "isIsolated");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedLike(String value) {
            addCriterion("IS_ISOLATED like", value, "isIsolated");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedNotLike(String value) {
            addCriterion("IS_ISOLATED not like", value, "isIsolated");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedIn(List<String> values) {
            addCriterion("IS_ISOLATED in", values, "isIsolated");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedNotIn(List<String> values) {
            addCriterion("IS_ISOLATED not in", values, "isIsolated");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedBetween(String value1, String value2) {
            addCriterion("IS_ISOLATED between", value1, value2, "isIsolated");
            return (Criteria) this;
        }

        public Criteria andIsIsolatedNotBetween(String value1, String value2) {
            addCriterion("IS_ISOLATED not between", value1, value2, "isIsolated");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CEC_EQUIPMENT
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}