package com.ibms.app.beans;

public class CecEquipment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_EQUIPMENT.EQUIPMENT_ID
     *
     * @mbggenerated
     */
    private String equipmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_EQUIPMENT.EQUIPMENT_NAME
     *
     * @mbggenerated
     */
    private String equipmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_EQUIPMENT.EQUIPMENT_TYPE_ID
     *
     * @mbggenerated
     */
    private String equipmentTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_EQUIPMENT.REGION_ID
     *
     * @mbggenerated
     */
    private String regionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_EQUIPMENT.EQUIPMENT_CODE
     *
     * @mbggenerated
     */
    private String equipmentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_EQUIPMENT.EQUIPMENT_ADDRESS
     *
     * @mbggenerated
     */
    private String equipmentAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CEC_EQUIPMENT.IS_ISOLATED
     *
     * @mbggenerated
     */
    private String isIsolated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_EQUIPMENT.EQUIPMENT_ID
     *
     * @return the value of CEC_EQUIPMENT.EQUIPMENT_ID
     *
     * @mbggenerated
     */
    public String getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_EQUIPMENT.EQUIPMENT_ID
     *
     * @param equipmentId the value for CEC_EQUIPMENT.EQUIPMENT_ID
     *
     * @mbggenerated
     */
    public void setEquipmentId(String equipmentId) {
        this.equipmentId = equipmentId == null ? null : equipmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_EQUIPMENT.EQUIPMENT_NAME
     *
     * @return the value of CEC_EQUIPMENT.EQUIPMENT_NAME
     *
     * @mbggenerated
     */
    public String getEquipmentName() {
        return equipmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_EQUIPMENT.EQUIPMENT_NAME
     *
     * @param equipmentName the value for CEC_EQUIPMENT.EQUIPMENT_NAME
     *
     * @mbggenerated
     */
    public void setEquipmentName(String equipmentName) {
        this.equipmentName = equipmentName == null ? null : equipmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_EQUIPMENT.EQUIPMENT_TYPE_ID
     *
     * @return the value of CEC_EQUIPMENT.EQUIPMENT_TYPE_ID
     *
     * @mbggenerated
     */
    public String getEquipmentTypeId() {
        return equipmentTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_EQUIPMENT.EQUIPMENT_TYPE_ID
     *
     * @param equipmentTypeId the value for CEC_EQUIPMENT.EQUIPMENT_TYPE_ID
     *
     * @mbggenerated
     */
    public void setEquipmentTypeId(String equipmentTypeId) {
        this.equipmentTypeId = equipmentTypeId == null ? null : equipmentTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_EQUIPMENT.REGION_ID
     *
     * @return the value of CEC_EQUIPMENT.REGION_ID
     *
     * @mbggenerated
     */
    public String getRegionId() {
        return regionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_EQUIPMENT.REGION_ID
     *
     * @param regionId the value for CEC_EQUIPMENT.REGION_ID
     *
     * @mbggenerated
     */
    public void setRegionId(String regionId) {
        this.regionId = regionId == null ? null : regionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_EQUIPMENT.EQUIPMENT_CODE
     *
     * @return the value of CEC_EQUIPMENT.EQUIPMENT_CODE
     *
     * @mbggenerated
     */
    public String getEquipmentCode() {
        return equipmentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_EQUIPMENT.EQUIPMENT_CODE
     *
     * @param equipmentCode the value for CEC_EQUIPMENT.EQUIPMENT_CODE
     *
     * @mbggenerated
     */
    public void setEquipmentCode(String equipmentCode) {
        this.equipmentCode = equipmentCode == null ? null : equipmentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_EQUIPMENT.EQUIPMENT_ADDRESS
     *
     * @return the value of CEC_EQUIPMENT.EQUIPMENT_ADDRESS
     *
     * @mbggenerated
     */
    public String getEquipmentAddress() {
        return equipmentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_EQUIPMENT.EQUIPMENT_ADDRESS
     *
     * @param equipmentAddress the value for CEC_EQUIPMENT.EQUIPMENT_ADDRESS
     *
     * @mbggenerated
     */
    public void setEquipmentAddress(String equipmentAddress) {
        this.equipmentAddress = equipmentAddress == null ? null : equipmentAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CEC_EQUIPMENT.IS_ISOLATED
     *
     * @return the value of CEC_EQUIPMENT.IS_ISOLATED
     *
     * @mbggenerated
     */
    public String getIsIsolated() {
        return isIsolated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CEC_EQUIPMENT.IS_ISOLATED
     *
     * @param isIsolated the value for CEC_EQUIPMENT.IS_ISOLATED
     *
     * @mbggenerated
     */
    public void setIsIsolated(String isIsolated) {
        this.isIsolated = isIsolated == null ? null : isIsolated.trim();
    }
}